version: "3.9"

services:
  app:
    build: .
    volumes:
      - ./src:/src:cached
    working_dir: "/src"
    ports:
      - "3000:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true